name: CI/CD Frontend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gustavokubiack/mail-front:latest
            gustavokubiack/mail-front:${{ github.sha }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Clone infra repository
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/gustavokubiack/mail-ops.git
          cd mail-ops
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Kustomize image
        run: |
          cd mail-ops/k8s/frontend
          kustomize edit set image gustavokubiack/mail-front=gustavokubiack/mail-front:${{ github.sha }}

      - name: Push changes to infra repo
        run: |
          cd mail-ops
          git add .
          git commit -m "Update frontend image to ${{ github.sha }}"
          git push origin main
